### PR TITLE
Update getting started

### PR DESCRIPTION
**Pull request by MedovTimur**

### CODE REVIEW

**Review by AndrePanin — APPROVED** [review]

**Comment by btwiuse** [comment]
According to community feedback, the guide should mention how to install cargo-gbuild and what it is for. Can that be added? @MedovTimur

**Comment by MedovTimur** [comment]
> According to community feedback, the guide should mention how to install cargo-gbuild and what it is for. Can that be added? @MedovTimur

Yes of course, I will add this information when this functionality is publicly available

**Comment by jekennedy** [comment]
I have some feedback on the "Upload program" section of the doc. When going through the flow, there are 5 steps instead of 4:
1. Click the `Upload Program` button, which opens a popup to upload your new program
2. In the popup, click the `Select File` button and navigate to the `.opt.wasm` file ...
3. Under the heading `Add metadata/sails`, on the right side of the page, click the `Select file` and navigate to the .idl file ...
4. Calculate gas....
5. Sign the transaction...

As a side note: although it's obvious, it may be worth mentioned that `curl` is a prerequisite. It could be included in step 1 for Ubuntu (macbooks include it by default, so nothing needed there).

**Comment by MedovTimur** [comment]
> I have some feedback on the "Upload program" section of the doc. When going through the flow, there are 5 steps instead of 4:
> 
> 1. Click the `Upload Program` button, which opens a popup to upload your new program
> 2. In the popup, click the `Select File` button and navigate to the `.opt.wasm` file ...
> 3. Under the heading `Add metadata/sails`, on the right side of the page, click the `Select file` and navigate to the .idl file ...
> 4. Calculate gas....
> 5. Sign the transaction...
> 
> As a side note: although it's obvious, it may be worth mentioned that `curl` is a prerequisite. It could be included in step 1 for Ubuntu (macbooks include it by default, so nothing needed there).

 I think explicit mention of the popup may be redundant. I would prefer the instructions to be simplified and focused on the basic steps. Also, what does the remark with url mean?

**Comment by jekennedy** [comment]
> > I have some feedback on the "Upload program" section of the doc. When going through the flow, there are 5 steps instead of 4:
> > 
> > 1. Click the `Upload Program` button, which opens a popup to upload your new program
> > 2. In the popup, click the `Select File` button and navigate to the `.opt.wasm` file ...
> > 3. Under the heading `Add metadata/sails`, on the right side of the page, click the `Select file` and navigate to the .idl file ...
> > 4. Calculate gas....
> > 5. Sign the transaction...
> > 
> > As a side note: although it's obvious, it may be worth mentioned that `curl` is a prerequisite. It could be included in step 1 for Ubuntu (macbooks include it by default, so nothing needed there).
> 
> I think explicit mention of the popup may be redundant. I would prefer the instructions to be simplified and focused on the basic steps. Also, what does the remark with url mean?

The thing that's confusing in the current steps 1 & 2: after clicking `Upload Program` button the popup has a button named `Select File`, and step 2 also mentions a `Select File` button. I was confused when I went through this the first time. Another option would be to mention the popup in step 1, and keep the other steps the same.

For the comment about `curl` command, someone from the community requested we add `curl` to the prerequisites, since it's not included by default in all Linux distributions.

**Comment by MedovTimur** [comment]
@jekennedy Please review the last change. I have made an effort to address all your suggestions.

**Pull request merged**
